backend:
  name: git-gateway
  branch: main

media_folder: "assets/blog"
public_folder: "/assets/blog"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    format: "frontmatter"
    extension: "md"

    fields:
      - { label: "Title", name: "title", widget: "string" }

      - { label: "Publish Date", name: "date", widget: "datetime" }

      - { label: "Featured Image", name: "cover", widget: "image", required: false }

      - { label: "Summary", name: "description", widget: "text" }

      - { label: "Tags", name: "tags", widget: "list", required: false }

      - { label: "Body", name: "body", widget: "markdown" }
